language: python
matrix:
  include:
    # Python 2.7
    - python: 2.7
      env: TOXENV=py27-django18
    - python: 2.7
      env: TOXENV=py27-django19
    - python: 2.7
      env: TOXENV=py27-django110

    # Python 3.4
    - python: 3.4
      env: TOXENV=py34-django18
    - python: 3.4
      env: TOXENV=py34-django19
    - python: 3.4
      env: TOXENV=py34-django110

    # Python 3.5
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.5
      env: TOXENV=py35-django19
    - python: 3.5
      env: TOXENV=py35-django110

    # pypy
    - python: pypy
      env: TOXENV=pypy-django18
    - python: pypy
      env: TOXENV=pypy-django19
    - python: pypy
      env: TOXENV=pypy-django110

before_install:
  - "wget http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz"
  - "tar -xf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz"
  - "sudo cp -r wkhtmltox/* /usr/"

install:
  - pip install tox
  - pip install codecov
  - pip install Django==1.10
  - pip install -r requirements/test.txt
  - pip install -r requirements/docs.txt

script:
  - tox
  - pylint django_pdfkit --cov=codecov
  - cd docs && make clean html

after_success:
  - bash <(curl -s https://codecov.io/bash)
